name: Create Release

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        name: Create release PR
        with:
          release-type: node

      # Uncomment these steps to enable automatic publishing to NPM
      # - uses: actions/checkout@v4
      #   name: Checkout code
      #   if: ${{ steps.release.outputs.release_created }}

      # - uses: actions/setup-node@v4
      #   name: Setup node
      #   with:
      #     node-version: 22
      #     registry-url: 'https://registry.npmjs.org'
      #   if: ${{ steps.release.outputs.release_created }}

      # - run: npm ci
      #   name: Install dependencies
      #   if: ${{ steps.release.outputs.release_created }}

      # - run: npm test
      #   name: Run tests
      #   if: ${{ steps.release.outputs.release_created }}

      # - run: npm publish
      #   name: Publish to NPM
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   if: ${{ steps.release.outputs.release_created }}
